platform :ios, '10.0'

use_frameworks!

def shared_pods    
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxGesture'
    pod 'RxDataSources'
    pod 'RxKeyboard'
    pod 'RxAnimated'
    
    pod 'Cartography'
end

target 'SocialBank' do
    shared_pods
end
