platform :ios, '10.0'

use_frameworks!

def shared_pods 
    pod 'Moya'
    pod 'SwiftyJSON'
   
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxGesture'
    pod 'RxDataSources'
    pod 'RxKeyboard'
    pod 'RxKeyboard'
    
    pod 'Cartography'
    pod 'SDWebImage'
    pod 'PKHUD'
    pod 'InputBarAccessoryView'
    pod 'InputMask'
pod 'MBCircularProgressBar'

end

target 'SocialBank' do
    shared_pods
end
